networks:
  default:
  dev-proxy:
    external: true

volumes:
  db-data:
  rds-data:
  elastic-data:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/images/php/Dockerfile.loc
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      STAND: loc
      APP_URL: http://${VIRTUAL_HOST}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-tmp}
      DB_NAME: ${DB_NAME:-laravel}
      ELASTIC_HOST: ${ELS_HOST:-elasticsearch}
      ELASTIC_PORT: ${ELS_PORT:-9200}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    volumes:
      - ./app:/var/www/html
#      - ./.git:/var/www/html/.git:ro
      - ./docker/images/php/configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug-plus.ini
    networks:
      - default
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-php.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-php.loadbalancer.server.port=80"
    depends_on:
      - db
      - redis
      - elasticsearch
    restart: unless-stopped

  db:
    image: mariadb:10.11
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS:-tmp}
        MYSQL_DATABASE: ${DB_NAME:-laravel}
    ports:
        -   "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - rds-data:/data
    restart: unless-stopped

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_USER: ${DB_USER:-root}
      PMA_PASSWORD: ${DB_PASS:-tmp}
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 1047527424
    expose:
      - 80
    networks:
      - default
      - dev-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-pma.rule=Host(`pma-${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-pma.loadbalancer.server.port=80"
    restart: unless-stopped

  npm:
    image: node:alpine
    depends_on:
      - php
    volumes:
        - ./app:/var/www/html
        - ./app/.env:/var/www/html/.env
    ports:
        - 3000:3000
        - 3001:3001
        - 5173:5173
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
        - default
        - dev-proxy

  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HEAP_SIZE=512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
